import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'he' | 'en' | 'ar' | 'de' | 'fr' | 'ka' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  he: {
    'app.title': 'סופר סטודיו מפיק',
    'app.subtitle': 'סטודיו מקצועי לכתיבת שירים',
    'tab.lyrics': 'מילים וכתיבה',
    'tab.arrangement': 'עיבוד וסאונד',
    'tab.composition': 'אקורדים ולחן',
    'btn.export': 'ייצוא פרויקט',
    'btn.new': 'פרויקט חדש',
    'btn.settings': 'הגדרות',
    'status.ready': 'ליבת AI מוכנה',
    'status.project': 'סטטוס פרויקט',
    'modal.new.title': 'להתחיל פרויקט חדש?',
    'modal.new.desc': 'פעולה זו תמחק את כל המילים, רעיונות העיבוד והלחנים הנוכחיים שלך. לא ניתן לבטל פעולה זו.',
    'modal.new.cancel': 'ביטול',
    'modal.new.confirm': 'נקה הכל',
    'settings.title': 'הגדרות מערכת',
    'settings.language': 'שפת ממשק',
    'settings.close': 'סגור',
    'export.txt': 'ייצוא כ-TXT',
    'export.doc': 'ייצוא כ-Word (.doc)',
    'export.pdf': 'ייצוא כ-PDF',
    'lyrics.topic.label': 'נושא או רעיון',
    'lyrics.topic.placeholder': 'על מה השיר? (למשל, לילה גשום בתל אביב, אהבה אבודה...)',
    'lyrics.lang.label': 'שפת השיר',
    'lyrics.gender.label': 'מגדר הזמר/ת',
    'lyrics.gender.male': 'זכר',
    'lyrics.gender.female': 'נקבה',
    'lyrics.btn.vocalize': 'ניקוד (הוספת ניקוד)',
    'lyrics.btn.vocalizing': 'מנקד...',
    'lyrics.btn.generate': 'צור מילים',
    'lyrics.btn.generating': 'יוצר...',
    'lyrics.btn.refine': 'שפר/לטש מילים',
    'lyrics.btn.refining': 'מלטש...',
    'lyrics.editor.label': 'עורך מילים',
    'lyrics.copy': 'העתק מילים',
    'lyrics.copied': 'הועתק!',
    'lyrics.word.manual': 'עריכה ידנית / ניקוד',
    'lyrics.word.replace': 'החלף מילה (AI)',
    'lyrics.word.nikud': 'הוסף/תקן ניקוד (AI)',
    'lyrics.word.delete': 'מחק מילה',
    'lyrics.word.add': 'הוסף מילה אחרי',
    'arrangement.idea.label': 'רעיון לעיבוד או סגנון',
    'arrangement.idea.placeholder': 'תאר את הסאונד שאתה מחפש... (למשל, בלדת פסנתר אינטימית, פופ אלקטרוני אנרגטי...)',
    'arrangement.btn.generate': 'צור הצעת עיבוד',
    'arrangement.result.label': 'הצעת עיבוד וסאונד',
    'composition.idea.label': 'רעיון ללחן או אקורדים',
    'composition.idea.placeholder': 'תאר את המלודיה או האקורדים... (למשל, אקורדים ג\'אזיים מורכבים, מלודיה קליטה ופשוטה...)',
    'composition.btn.generate': 'צור הצעת לחן',
    'composition.result.label': 'הצעת אקורדים ומלודיה',
  },
  en: {
    'app.title': 'SUPER STUDIO PRODUCER',
    'app.subtitle': 'Professional Songwriting Studio',
    'tab.lyrics': 'Lyrics & Writing',
    'tab.arrangement': 'Arrangement & Sound',
    'tab.composition': 'Chords & Melody',
    'btn.export': 'Export Project',
    'btn.new': 'New Project',
    'btn.settings': 'Settings',
    'status.ready': 'AI Core Ready',
    'status.project': 'Project Status',
    'modal.new.title': 'Start New Project?',
    'modal.new.desc': 'This will clear all your current lyrics, arrangement ideas, and musical compositions. This action cannot be undone.',
    'modal.new.cancel': 'Cancel',
    'modal.new.confirm': 'Clear Everything',
    'settings.title': 'System Settings',
    'settings.language': 'Interface Language',
    'settings.close': 'Close',
    'export.txt': 'Export as TXT',
    'export.doc': 'Export as Word (.doc)',
    'export.pdf': 'Export as PDF',
    'lyrics.topic.label': 'Topic or Idea',
    'lyrics.topic.placeholder': 'What is the song about? (e.g., A rainy night in Tel Aviv, a lost love...)',
    'lyrics.lang.label': 'Song Language',
    'lyrics.gender.label': 'Singer Gender',
    'lyrics.gender.male': 'Male',
    'lyrics.gender.female': 'Female',
    'lyrics.btn.vocalize': 'Vocalize (Add Nikud)',
    'lyrics.btn.vocalizing': 'Vocalizing...',
    'lyrics.btn.generate': 'Generate Lyrics',
    'lyrics.btn.generating': 'Generating...',
    'lyrics.btn.refine': 'Improve/Refine Lyrics',
    'lyrics.btn.refining': 'Refining...',
    'lyrics.editor.label': 'Lyrics Editor',
    'lyrics.copy': 'Copy Lyrics',
    'lyrics.copied': 'Copied!',
    'lyrics.word.manual': 'Manual Edit / Nikud',
    'lyrics.word.replace': 'Replace Word (AI)',
    'lyrics.word.nikud': 'Add/Fix Nikud (AI)',
    'lyrics.word.delete': 'Delete Word',
    'lyrics.word.add': 'Add Word After',
    'arrangement.idea.label': 'Arrangement or Style Idea',
    'arrangement.idea.placeholder': 'Describe the sound you are looking for... (e.g., Intimate piano ballad, energetic electronic pop...)',
    'arrangement.btn.generate': 'Generate Arrangement Suggestion',
    'arrangement.result.label': 'Arrangement & Sound Suggestion',
    'composition.idea.label': 'Composition or Chords Idea',
    'composition.idea.placeholder': 'Describe the melody or chords... (e.g., Complex jazzy chords, catchy and simple melody...)',
    'composition.btn.generate': 'Generate Composition Suggestion',
    'composition.result.label': 'Chords & Melody Suggestion',
  },
  ar: {
    'app.title': 'سوبر ستوديو برودوسر',
    'app.subtitle': 'استوديو احترافي لكتابة الأغاني',
    'tab.lyrics': 'الكلمات والكتابة',
    'tab.arrangement': 'التوزيع والصوت',
    'tab.composition': 'الألحان والنغمات',
    'btn.export': 'تصدير المشروع',
    'btn.new': 'مشروع جديد',
    'btn.settings': 'الإعدادات',
    'status.ready': 'نواة الذكاء الاصطناعي جاهزة',
    'status.project': 'حالة المشروع',
    'modal.new.title': 'بدء مشروع جديد؟',
    'modal.new.desc': 'سيؤدي هذا إلى مسح جميع كلمات الأغاني الحالية وأفكار التوزيع والألحان الموسيقية. لا يمكن التراجع عن هذا الإجراء.',
    'modal.new.cancel': 'إلغاء',
    'modal.new.confirm': 'مسح الكل',
    'settings.title': 'إعدادات النظام',
    'settings.language': 'لغة الواجهة',
    'settings.close': 'إغلاق',
    'export.txt': 'تصدير كـ TXT',
    'export.doc': 'تصدير كـ Word (.doc)',
    'export.pdf': 'تصدير كـ PDF',
    'lyrics.topic.label': 'الموضوع أو الفكرة',
    'lyrics.topic.placeholder': 'عن ماذا تتحدث الأغنية؟ (مثلاً: ليلة ممطرة في تل أبيب، حب مفقود...)',
    'lyrics.lang.label': 'لغة الأغنية',
    'lyrics.gender.label': 'جنس المغني',
    'lyrics.gender.male': 'ذكر',
    'lyrics.gender.female': 'أنثى',
    'lyrics.btn.vocalize': 'تشكيل (إضافة الحركات)',
    'lyrics.btn.vocalizing': 'جاري التشكيل...',
    'lyrics.btn.generate': 'توليد الكلمات',
    'lyrics.btn.generating': 'جاري التوليد...',
    'lyrics.btn.refine': 'تحسين/تنقيح الكلمات',
    'lyrics.btn.refining': 'جاري التحسين...',
    'lyrics.editor.label': 'محرر الكلمات',
    'lyrics.copy': 'نسخ الكلمات',
    'lyrics.copied': 'تم النسخ!',
    'lyrics.word.manual': 'تعديل يدوي / تشكيل',
    'lyrics.word.replace': 'استبدال الكلمة (AI)',
    'lyrics.word.nikud': 'إضافة/تصحيح التشكيل (AI)',
    'lyrics.word.delete': 'حذف الكلمة',
    'lyrics.word.add': 'إضافة كلمة بعد',
    'arrangement.idea.label': 'فكرة التوزيع أو النمط',
    'arrangement.idea.placeholder': 'صف الصوت الذي تبحث عنه... (مثلاً: بالاد بيانو حميم، بوب إلكتروني حيوي...)',
    'arrangement.btn.generate': 'توليد اقتراح التوزيع',
    'arrangement.result.label': 'اقتراح التوزيع والصوت',
    'composition.idea.label': 'فكرة اللحن أو الأوتار',
    'composition.idea.placeholder': 'صف اللحن أو الأوتار... (مثلاً: أوتار جاز معقدة، لحن بسيط وجذاب...)',
    'composition.btn.generate': 'توليد اقتراح اللحن',
    'composition.result.label': 'اقتراح الأوتار واللحن',
  },
  de: {
    'app.title': 'SUPER STUDIO PRODUCER',
    'app.subtitle': 'Professionelles Songwriting-Studio',
    'tab.lyrics': 'Lyrics & Schreiben',
    'tab.arrangement': 'Arrangement & Sound',
    'tab.composition': 'Akkorde & Melodie',
    'btn.export': 'Projekt exportieren',
    'btn.new': 'Neues Projekt',
    'btn.settings': 'Einstellungen',
    'status.ready': 'KI-Kern bereit',
    'status.project': 'Projektstatus',
    'modal.new.title': 'Neues Projekt starten?',
    'modal.new.desc': 'Dadurch werden alle Ihre aktuellen Texte, Arrangement-Ideen und musikalischen Kompositionen gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
    'modal.new.cancel': 'Abbrechen',
    'modal.new.confirm': 'Alles löschen',
    'settings.title': 'Systemeinstellungen',
    'settings.language': 'Oberflächensprache',
    'settings.close': 'Schließen',
    'export.txt': 'Als TXT exportieren',
    'export.doc': 'Als Word (.doc) exportieren',
    'export.pdf': 'Als PDF exportieren',
    'lyrics.topic.label': 'Thema oder Idee',
    'lyrics.topic.placeholder': 'Wovon handelt das Lied? (z.B. Eine regnerische Nacht in Tel Aviv, eine verlorene Liebe...)',
    'lyrics.lang.label': 'Liedsprache',
    'lyrics.gender.label': 'Geschlecht des Sängers',
    'lyrics.gender.male': 'Männlich',
    'lyrics.gender.female': 'Weiblich',
    'lyrics.btn.vocalize': 'Vokalisieren (Nikud hinzufügen)',
    'lyrics.btn.vocalizing': 'Vokalisierung...',
    'lyrics.btn.generate': 'Lyrics generieren',
    'lyrics.btn.generating': 'Generierung...',
    'lyrics.btn.refine': 'Lyrics verbessern/verfeinern',
    'lyrics.btn.refining': 'Verfeinerung...',
    'lyrics.editor.label': 'Lyrics-Editor',
    'lyrics.copy': 'Lyrics kopieren',
    'lyrics.copied': 'Kopiert!',
    'lyrics.word.manual': 'Manuelle Bearbeitung / Nikud',
    'lyrics.word.replace': 'Wort ersetzen (KI)',
    'lyrics.word.nikud': 'Nikud hinzufügen/korrigieren (KI)',
    'lyrics.word.delete': 'Wort löschen',
    'lyrics.word.add': 'Wort danach hinzufügen',
    'arrangement.idea.label': 'Arrangement- oder Stilidee',
    'arrangement.idea.placeholder': 'Beschreiben Sie den Sound, den Sie suchen... (z.B. Intime Klavierballade, energetischer Electro-Pop...)',
    'arrangement.btn.generate': 'Arrangement-Vorschlag generieren',
    'arrangement.result.label': 'Arrangement- & Sound-Vorschlag',
    'composition.idea.label': 'Kompositions- oder Akkordidee',
    'composition.idea.placeholder': 'Beschreiben Sie die Melodie oder Akkorde... (z.B. Komplexe Jazz-Akkorde, eingängige und einfache Melodie...)',
    'composition.btn.generate': 'Kompositions-Vorschlag generieren',
    'composition.result.label': 'Akkord- & Melodie-Vorschlag',
  },
  fr: {
    'app.title': 'SUPER STUDIO PRODUCER',
    'app.subtitle': 'Studio d\'écriture de chansons professionnel',
    'tab.lyrics': 'Paroles & Écriture',
    'tab.arrangement': 'Arrangement & Son',
    'tab.composition': 'Accords & Mélodie',
    'btn.export': 'Exporter le projet',
    'btn.new': 'Nouveau projet',
    'btn.settings': 'Paramètres',
    'status.ready': 'Cœur IA prêt',
    'status.project': 'Statut du projet',
    'modal.new.title': 'Démarrer un nouveau projet ?',
    'modal.new.desc': 'Cela effacera toutes vos paroles actuelles, vos idées d\'arrangement et vos compositions musicales. Cette action est irréversible.',
    'modal.new.cancel': 'Annuler',
    'modal.new.confirm': 'Tout effacer',
    'settings.title': 'Paramètres du système',
    'settings.language': 'Langue de l\'interface',
    'settings.close': 'Fermer',
    'export.txt': 'Exporter en TXT',
    'export.doc': 'Exporter en Word (.doc)',
    'export.pdf': 'Exporter en PDF',
    'lyrics.topic.label': 'Sujet ou idée',
    'lyrics.topic.placeholder': 'De quoi parle la chanson ? (par ex., Une nuit pluvieuse à Tel Aviv, un amour perdu...)',
    'lyrics.lang.label': 'Langue de la chanson',
    'lyrics.gender.label': 'Sexe du chanteur',
    'lyrics.gender.male': 'Homme',
    'lyrics.gender.female': 'Femme',
    'lyrics.btn.vocalize': 'Vocaliser (Ajouter Nikud)',
    'lyrics.btn.vocalizing': 'Vocalisation...',
    'lyrics.btn.generate': 'Générer les paroles',
    'lyrics.btn.generating': 'Génération...',
    'lyrics.btn.refine': 'Améliorer/Affiner les paroles',
    'lyrics.btn.refining': 'Affinage...',
    'lyrics.editor.label': 'Éditeur de paroles',
    'lyrics.copy': 'Copier les paroles',
    'lyrics.copied': 'Copié !',
    'lyrics.word.manual': 'Édition manuelle / Nikud',
    'lyrics.word.replace': 'Remplacer le mot (IA)',
    'lyrics.word.nikud': 'Ajouter/Corriger Nikud (IA)',
    'lyrics.word.delete': 'Supprimer le mot',
    'lyrics.word.add': 'Ajouter un mot après',
    'arrangement.idea.label': 'Idée d\'arrangement ou de style',
    'arrangement.idea.placeholder': 'Décrivez le son que vous recherchez... (par ex., Ballade au piano intime, pop électronique énergique...)',
    'arrangement.btn.generate': 'Générer une suggestion d\'arrangement',
    'arrangement.result.label': 'Suggestion d\'arrangement et de son',
    'composition.idea.label': 'Idée de composition ou d\'accords',
    'composition.idea.placeholder': 'Décrivez la mélodie ou les accords... (par ex., Accords de jazz complexes, mélodie simple et entraînante...)',
    'composition.btn.generate': 'Générer une suggestion de composition',
    'composition.result.label': 'Suggestion d\'accords et de mélodie',
  },
  ka: {
    'app.title': 'SUPER STUDIO PRODUCER',
    'app.subtitle': 'პროფესიონალური სიმღერების წერის სტუდია',
    'tab.lyrics': 'ტექსტი და წერა',
    'tab.arrangement': 'არანჟირება და ხმა',
    'tab.composition': 'აკორდები და მელოდია',
    'btn.export': 'პროექტის ექსპორტი',
    'btn.new': 'ახალი პროექტი',
    'btn.settings': 'პარამეტრები',
    'status.ready': 'AI ბირთვი მზადაა',
    'status.project': 'პროექტის სტატუსი',
    'modal.new.title': 'დავიწყოთ ახალი პროექტი?',
    'modal.new.desc': 'ეს წაშლის თქვენს ყველა მიმდინარე ტექსტს, არანჟირების იდეას და მუსიკალურ კომპოზიციას. ამ მოქმედების გაუქმება შეუძლებელია.',
    'modal.new.cancel': 'გაუქმება',
    'modal.new.confirm': 'ყველაფრის წაშლა',
    'settings.title': 'სისტემის პარამეტრები',
    'settings.language': 'ინტერფეისის ენა',
    'settings.close': 'დახურვა',
    'export.txt': 'ექსპორტი TXT ფორმატში',
    'export.doc': 'ექსპორტი Word (.doc) ფორმატში',
    'export.pdf': 'ექსპორტი PDF ფორმატში',
    'lyrics.topic.label': 'თემა ან იდეა',
    'lyrics.topic.placeholder': 'რაზეა სიმღერა? (მაგ., წვიმიანი ღამე თელ-ავივში, დაკარგული სიყვარული...)',
    'lyrics.lang.label': 'სიმღერის ენა',
    'lyrics.gender.label': 'მომღერლის სქესი',
    'lyrics.gender.male': 'მამაკაცი',
    'lyrics.gender.female': 'ქალი',
    'lyrics.btn.vocalize': 'ვოკალიზაცია (ნიკუდის დამატება)',
    'lyrics.btn.vocalizing': 'ვოკალიზაცია...',
    'lyrics.btn.generate': 'ტექსტის გენერირება',
    'lyrics.btn.generating': 'გენერირება...',
    'lyrics.btn.refine': 'ტექსტის გაუმჯობესება/დახვეწა',
    'lyrics.btn.refining': 'დახვეწა...',
    'lyrics.editor.label': 'ტექსტის რედაქტორი',
    'lyrics.copy': 'ტექსტის კოპირება',
    'lyrics.copied': 'დაკოპირდა!',
    'lyrics.word.manual': 'მექანიკური რედაქტირება / ნიკუდი',
    'lyrics.word.replace': 'სიტყვის შეცვლა (AI)',
    'lyrics.word.nikud': 'ნიკუდის დამატება/გასწორება (AI)',
    'lyrics.word.delete': 'სიტყვის წაშლა',
    'lyrics.word.add': 'სიტყვის დამატება შემდეგ',
    'arrangement.idea.label': 'არანჟირების ან სტილის იდეა',
    'arrangement.idea.placeholder': 'აღწერეთ ხმა, რომელსაც ეძებთ... (მაგ., ინტიმური საფორტეპიანო ბალადა, ენერგიული ელექტრონული პოპი...)',
    'arrangement.btn.generate': 'არანჟირების შეთავაზების გენერირება',
    'arrangement.result.label': 'არანჟირებისა და ხმის შეთავაზება',
    'composition.idea.label': 'კომპოზიციის ან აკორდების იდეა',
    'composition.idea.placeholder': 'აღწერეთ მელოდია ან აკორდები... (მაგ., რთული ჯაზური აკორდები, დასამახსოვრებელი და მარტივი მელოდია...)',
    'composition.btn.generate': 'კომპოზიციის შეთავაზების გენერირება',
    'composition.result.label': 'აკორდებისა და მელოდიის შეთავაზება',
  },
  ru: {
    'app.title': 'SUPER STUDIO PRODUCER',
    'app.subtitle': 'Профессиональная студия написания песен',
    'tab.lyrics': 'Текст и написание',
    'tab.arrangement': 'Аранжировка и звук',
    'tab.composition': 'Аккорды и мелодия',
    'btn.export': 'Экспорт проекта',
    'btn.new': 'Новый проект',
    'btn.settings': 'Настройки',
    'status.ready': 'Ядро ИИ готово',
    'status.project': 'Статус проекта',
    'modal.new.title': 'Начать новый проект?',
    'modal.new.desc': 'Это удалит все ваши текущие тексты, идеи аранжировок и музыкальные композиции. Это действие нельзя отменить.',
    'modal.new.cancel': 'Отмена',
    'modal.new.confirm': 'Очистить всё',
    'settings.title': 'Системные настройки',
    'settings.language': 'Язык интерфейса',
    'settings.close': 'Закрыть',
    'export.txt': 'Экспорт в TXT',
    'export.doc': 'Экспорт в Word (.doc)',
    'export.pdf': 'Экспорт в PDF',
    'lyrics.topic.label': 'Тема или идея',
    'lyrics.topic.placeholder': 'О чем песня? (например, Дождливая ночь в Тель-Авиве, потерянная любовь...)',
    'lyrics.lang.label': 'Язык песни',
    'lyrics.gender.label': 'Пол певца',
    'lyrics.gender.male': 'Мужской',
    'lyrics.gender.female': 'Женский',
    'lyrics.btn.vocalize': 'Вокализация (добавить никуд)',
    'lyrics.btn.vocalizing': 'Вокализация...',
    'lyrics.btn.generate': 'Создать текст',
    'lyrics.btn.generating': 'Создание...',
    'lyrics.btn.refine': 'Улучшить текст',
    'lyrics.btn.refining': 'Улучшение...',
    'lyrics.editor.label': 'Редактор текста',
    'lyrics.copy': 'Копировать текст',
    'lyrics.copied': 'Скопировано!',
    'lyrics.word.manual': 'Ручная правка / Никуд',
    'lyrics.word.replace': 'Заменить слово (ИИ)',
    'lyrics.word.nikud': 'Добавить/исправить никуд (ИИ)',
    'lyrics.word.delete': 'Удалить слово',
    'lyrics.word.add': 'Добавить слово после',
    'arrangement.idea.label': 'Идея аранжировки или стиля',
    'arrangement.idea.placeholder': 'Опишите звук, который вы ищете... (например, Интимная фортепианная баллада, энергичный электро-поп...)',
    'arrangement.btn.generate': 'Создать предложение по аранжировке',
    'arrangement.result.label': 'Предложение по аранжировке и звуку',
    'composition.idea.label': 'Идея композиции или аккордов',
    'composition.idea.placeholder': 'Опишите мелодию или аккорды... (например, Сложные джазовые аккорды, запоминающаяся и простая мелодия...)',
    'composition.btn.generate': 'Создать предложение по композиции',
    'composition.result.label': 'Предложение по аккордам и мелодии',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'he';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'he' || language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div className={isRTL ? 'font-hebrew' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
